### ISSUE TITLE
Export Button Doesn't Work (web version)

### ISSUE THREAD

**Issue by alijaya** [patriciogonzalezvivo/glslEditor#41]
All except Download File doesn't work.

**Comment by patriciogonzalezvivo** [comment]
Hi! I belive this is fixed... was an issue of SSL keys on the server

**Comment by jcnesci** [comment]
@patriciogonzalezvivo Still doesn't work for me at this time.
Does it really work for you?
```
Chrome: Version 70.0.3538.110 (Official Build) (64-bit)
OSX High Sierra
```

**Comment by willstall** [comment]
I am still having this issue via:
http://editor.thebookofshaders.com

**Comment by MichaPau** [comment]
I get this error message trying the Export button:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://thebookofshaders.com:8080/save. (Reason: CORS request did not succeed)`

Firefox 72.0.2 (64-bit)

**Comment by Chusynuk** [comment]
Getting this error in console once I try to export to `Openframe` .
Do we have any updates?

Chrome Version 81.0.4044.92 (64-bit) OSX 10.14.6

<img width="1678" alt="Screenshot 2020-04-11 at 13 48 50" src="https://user-images.githubusercontent.com/4323435/79042845-5e75af00-7bfb-11ea-9aea-1736802cdb01.png">
